import {
  type MigrationProject,
  type AssessmentResult,
  type DashboardStats,
  type ActivityEntry,
  MigrationStatus,
  MigrationType,
  AdobeProduct,
  Severity,
  CompatibilityLevel,
  PhaseType,
  ComplianceFramework,
} from '@/types';

// ============================================================
// Dashboard Stats
// ============================================================

export const mockDashboardStats: DashboardStats = {
  totalMigrations: 47,
  activeMigrations: 12,
  completedMigrations: 31,
  totalItemsMigrated: 284_650,
  averageTimeSavings: 68,
  averageCostSavings: 54,
  topMigrationTypes: [
    { type: MigrationType.AEM_ONPREM_TO_CLOUD, count: 14, label: 'AEM On-Prem to Cloud' },
    { type: MigrationType.GA_TO_CJA, count: 9, label: 'GA to Customer Journey Analytics' },
    { type: MigrationType.WORDPRESS_TO_AEM, count: 7, label: 'WordPress to AEM' },
    { type: MigrationType.AAM_TO_RTCDP, count: 6, label: 'AAM to Real-Time CDP' },
    { type: MigrationType.CAMPAIGN_CLASSIC_TO_V8, count: 5, label: 'Campaign Classic to v8' },
  ],
  recentActivity: [],
};

// ============================================================
// Migration Projects
// ============================================================

export const mockMigrations: MigrationProject[] = [
  {
    id: 'mig-001',
    name: 'Acme Corp AEM Cloud Migration',
    organizationId: 'org-acme',
    organizationName: 'Acme Corporation',
    migrationType: MigrationType.AEM_ONPREM_TO_CLOUD,
    status: MigrationStatus.EXECUTING,
    productsInScope: [AdobeProduct.AEM_SITES, AdobeProduct.AEM_ASSETS, AdobeProduct.AEM_FORMS],
    complianceRequirements: [ComplianceFramework.GDPR, ComplianceFramework.SOX],
    sourceEnvironment: {
      platform: 'aem_6x',
      version: '6.5.17',
      url: 'https://author.acme.com',
      connectionType: 'api',
      credentials: null,
      metadata: { javaVersion: '11', osgiComponents: 342 },
    },
    targetEnvironment: {
      platform: 'aem_cloud',
      organizationId: 'acme-org-id',
      programId: 'prog-12345',
      environmentId: 'env-prod',
      url: 'https://author-p12345-e67890.adobeaemcloud.com',
      credentials: null,
      metadata: {},
    },
    assessment: null,
    phases: [
      {
        id: 'phase-1',
        type: PhaseType.ASSESSMENT,
        name: 'Assessment',
        status: MigrationStatus.COMPLETED,
        progress: 100,
        items: [],
        startedAt: '2026-01-15T10:00:00Z',
        completedAt: '2026-01-16T14:30:00Z',
        estimatedDuration: 8,
        actualDuration: 6,
      },
      {
        id: 'phase-2',
        type: PhaseType.CODE_MODERNIZATION,
        name: 'Code Modernization',
        status: MigrationStatus.COMPLETED,
        progress: 100,
        items: [],
        startedAt: '2026-01-17T09:00:00Z',
        completedAt: '2026-01-24T16:00:00Z',
        estimatedDuration: 40,
        actualDuration: 35,
      },
      {
        id: 'phase-3',
        type: PhaseType.CONTENT_MIGRATION,
        name: 'Content Migration',
        status: MigrationStatus.EXECUTING,
        progress: 72,
        items: [],
        startedAt: '2026-01-25T09:00:00Z',
        completedAt: null,
        estimatedDuration: 24,
        actualDuration: null,
      },
      {
        id: 'phase-4',
        type: PhaseType.TESTING,
        name: 'Testing & Validation',
        status: MigrationStatus.DRAFT,
        progress: 0,
        items: [],
        startedAt: null,
        completedAt: null,
        estimatedDuration: 16,
        actualDuration: null,
      },
    ],
    riskScore: 0.3,
    estimatedDurationWeeks: 6,
    estimatedCost: 45000,
    actualCost: 38000,
    progress: 72,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-03-20T15:30:00Z',
    targetCompletionDate: '2026-04-15T00:00:00Z',
    completedAt: null,
  },
  {
    id: 'mig-002',
    name: 'GlobalBank Analytics to CJA',
    organizationId: 'org-gbank',
    organizationName: 'Global Banking Corp',
    migrationType: MigrationType.GA_TO_CJA,
    status: MigrationStatus.COMPLETED,
    productsInScope: [AdobeProduct.CJA, AdobeProduct.AEP],
    complianceRequirements: [ComplianceFramework.PCI_DSS, ComplianceFramework.GDPR],
    sourceEnvironment: {
      platform: 'ga4',
      version: '4.0',
      url: null,
      connectionType: 'api',
      credentials: null,
      metadata: { properties: 12, customDimensions: 45 },
    },
    targetEnvironment: {
      platform: 'cja',
      organizationId: 'gbank-org',
      programId: null,
      environmentId: null,
      url: 'https://experience.adobe.com',
      credentials: null,
      metadata: {},
    },
    assessment: null,
    phases: [],
    riskScore: 0.15,
    estimatedDurationWeeks: 4,
    estimatedCost: 28000,
    actualCost: 22500,
    progress: 100,
    createdAt: '2025-11-05T08:00:00Z',
    updatedAt: '2026-01-20T12:00:00Z',
    targetCompletionDate: '2026-01-30T00:00:00Z',
    completedAt: '2026-01-20T12:00:00Z',
  },
  {
    id: 'mig-003',
    name: 'TechStart WordPress to AEM EDS',
    organizationId: 'org-techstart',
    organizationName: 'TechStart Inc',
    migrationType: MigrationType.WORDPRESS_TO_AEM,
    status: MigrationStatus.ASSESSING,
    productsInScope: [AdobeProduct.AEM_EDS],
    complianceRequirements: [],
    sourceEnvironment: {
      platform: 'wordpress',
      version: '6.4',
      url: 'https://techstart.com',
      connectionType: 'api',
      credentials: null,
      metadata: { posts: 2400, pages: 180, plugins: 34 },
    },
    targetEnvironment: {
      platform: 'aem_eds',
      organizationId: 'techstart-org',
      programId: null,
      environmentId: null,
      url: null,
      credentials: null,
      metadata: {},
    },
    assessment: null,
    phases: [],
    riskScore: 0.45,
    estimatedDurationWeeks: 8,
    estimatedCost: 52000,
    actualCost: null,
    progress: 15,
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-19T10:00:00Z',
    targetCompletionDate: '2026-05-30T00:00:00Z',
    completedAt: null,
  },
  {
    id: 'mig-004',
    name: 'RetailMax Shopify to Adobe Commerce',
    organizationId: 'org-retailmax',
    organizationName: 'RetailMax Group',
    migrationType: MigrationType.SHOPIFY_TO_COMMERCE,
    status: MigrationStatus.PLANNING,
    productsInScope: [AdobeProduct.COMMERCE, AdobeProduct.AEP],
    complianceRequirements: [ComplianceFramework.PCI_DSS],
    sourceEnvironment: {
      platform: 'shopify',
      version: 'plus',
      url: 'https://retailmax.myshopify.com',
      connectionType: 'api',
      credentials: null,
      metadata: { products: 18500, orders: 450000 },
    },
    targetEnvironment: {
      platform: 'adobe_commerce',
      organizationId: 'retailmax-org',
      programId: null,
      environmentId: null,
      url: null,
      credentials: null,
      metadata: {},
    },
    assessment: null,
    phases: [],
    riskScore: 0.55,
    estimatedDurationWeeks: 12,
    estimatedCost: 95000,
    actualCost: null,
    progress: 25,
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-03-18T14:00:00Z',
    targetCompletionDate: '2026-07-01T00:00:00Z',
    completedAt: null,
  },
  {
    id: 'mig-005',
    name: 'HealthPlus Campaign v8 Upgrade',
    organizationId: 'org-healthplus',
    organizationName: 'HealthPlus Medical',
    migrationType: MigrationType.CAMPAIGN_CLASSIC_TO_V8,
    status: MigrationStatus.VALIDATING,
    productsInScope: [AdobeProduct.CAMPAIGN, AdobeProduct.AJO],
    complianceRequirements: [ComplianceFramework.HIPAA, ComplianceFramework.GDPR],
    sourceEnvironment: {
      platform: 'campaign_classic',
      version: '7.3',
      url: null,
      connectionType: 'api',
      credentials: null,
      metadata: { workflows: 234, deliveryTemplates: 89 },
    },
    targetEnvironment: {
      platform: 'campaign_v8',
      organizationId: 'healthplus-org',
      programId: null,
      environmentId: null,
      url: null,
      credentials: null,
      metadata: {},
    },
    assessment: null,
    phases: [],
    riskScore: 0.25,
    estimatedDurationWeeks: 5,
    estimatedCost: 35000,
    actualCost: 31000,
    progress: 92,
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-03-20T09:00:00Z',
    targetCompletionDate: '2026-03-28T00:00:00Z',
    completedAt: null,
  },
  {
    id: 'mig-006',
    name: 'MediaGroup DAM Consolidation',
    organizationId: 'org-mediagroup',
    organizationName: 'MediaGroup International',
    migrationType: MigrationType.DAM_TO_AEM_ASSETS,
    status: MigrationStatus.TRANSFORMING,
    productsInScope: [AdobeProduct.AEM_ASSETS, AdobeProduct.GENSTUDIO],
    complianceRequirements: [ComplianceFramework.GDPR],
    sourceEnvironment: {
      platform: 'bynder',
      version: '3.x',
      url: 'https://mediagroup.bynder.com',
      connectionType: 'api',
      credentials: null,
      metadata: { assets: 1_250_000, collections: 890 },
    },
    targetEnvironment: {
      platform: 'aem_assets_cloud',
      organizationId: 'mediagroup-org',
      programId: 'prog-67890',
      environmentId: 'env-assets',
      url: null,
      credentials: null,
      metadata: {},
    },
    assessment: null,
    phases: [],
    riskScore: 0.4,
    estimatedDurationWeeks: 10,
    estimatedCost: 78000,
    actualCost: null,
    progress: 45,
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-03-19T16:00:00Z',
    targetCompletionDate: '2026-05-15T00:00:00Z',
    completedAt: null,
  },
];

// ============================================================
// Assessment Result (for Acme Corp)
// ============================================================

export const mockAssessmentResult: AssessmentResult = {
  id: 'assess-001',
  migrationProjectId: 'mig-001',
  overallScore: 74,
  codeCompatibilityScore: 68,
  contentReadinessScore: 85,
  integrationComplexityScore: 62,
  configurationReadinessScore: 78,
  complianceScore: 91,
  findings: [
    {
      id: 'f-001',
      category: 'Code',
      subCategory: 'OSGi Components',
      severity: Severity.HIGH,
      compatibilityLevel: CompatibilityLevel.MANUAL_FIX,
      title: 'Custom OSGi service uses deprecated ResourceResolverFactory',
      description: 'The ResourceResolverFactory.getAdministrativeResourceResolver() method is deprecated and removed in AEM as a Cloud Service.',
      affectedPath: '/apps/acme/core/src/main/java/com/acme/core/services/ContentService.java',
      remediationGuide: 'Replace with ServiceResourceResolver pattern using service user mappings.',
      autoFixAvailable: false,
      estimatedHours: 4,
      bpaPatternCode: 'ACV-OSGi-001',
    },
    {
      id: 'f-002',
      category: 'Code',
      subCategory: 'Sling Models',
      severity: Severity.MEDIUM,
      compatibilityLevel: CompatibilityLevel.AUTO_FIXABLE,
      title: 'Sling Model uses @Reference instead of @OSGiService',
      description: 'Legacy @Reference annotation should be replaced with @OSGiService for Cloud Service compatibility.',
      affectedPath: '/apps/acme/core/src/main/java/com/acme/core/models/HeroModel.java',
      remediationGuide: 'Replace @Reference with @OSGiService annotation.',
      autoFixAvailable: true,
      estimatedHours: 0.5,
      bpaPatternCode: 'ACV-SLM-003',
    },
    {
      id: 'f-003',
      category: 'Content',
      subCategory: 'Templates',
      severity: Severity.HIGH,
      compatibilityLevel: CompatibilityLevel.MANUAL_FIX,
      title: 'Static templates must be converted to editable templates',
      description: '23 static templates detected that need conversion to editable templates for Cloud Service.',
      affectedPath: '/apps/acme/templates',
      remediationGuide: 'Create equivalent editable templates in /conf/acme/settings/wcm/templates.',
      autoFixAvailable: false,
      estimatedHours: 16,
      bpaPatternCode: 'ACV-TPL-001',
    },
    {
      id: 'f-004',
      category: 'Integration',
      subCategory: 'Authentication',
      severity: Severity.CRITICAL,
      compatibilityLevel: CompatibilityLevel.BLOCKER,
      title: 'LDAP authentication not supported in Cloud Service',
      description: 'Direct LDAP authentication configured via OSGi is not available in AEM as a Cloud Service.',
      affectedPath: '/apps/system/config/org.apache.jackrabbit.oak.security.authentication.ldap.LdapIdentityProvider.config',
      remediationGuide: 'Migrate to Adobe IMS integration with SAML 2.0 SSO.',
      autoFixAvailable: false,
      estimatedHours: 24,
      bpaPatternCode: null,
    },
    {
      id: 'f-005',
      category: 'Configuration',
      subCategory: 'Dispatcher',
      severity: Severity.MEDIUM,
      compatibilityLevel: CompatibilityLevel.AUTO_FIXABLE,
      title: 'Dispatcher rules use legacy syntax',
      description: 'Dispatcher configuration uses legacy /filter syntax incompatible with Cloud Service SDK.',
      affectedPath: '/dispatcher/src/conf.d/available_filters',
      remediationGuide: 'Update to Cloud Service dispatcher configuration structure.',
      autoFixAvailable: true,
      estimatedHours: 2,
      bpaPatternCode: 'ACV-DSP-001',
    },
    {
      id: 'f-006',
      category: 'Code',
      subCategory: 'Workflows',
      severity: Severity.LOW,
      compatibilityLevel: CompatibilityLevel.COMPATIBLE,
      title: 'Custom workflow step uses standard API',
      description: 'Custom workflow process step implementation is compatible with Cloud Service.',
      affectedPath: '/apps/acme/core/src/main/java/com/acme/core/workflow/ApprovalStep.java',
      remediationGuide: 'No action required.',
      autoFixAvailable: false,
      estimatedHours: 0,
      bpaPatternCode: null,
    },
    {
      id: 'f-007',
      category: 'Content',
      subCategory: 'Assets',
      severity: Severity.INFO,
      compatibilityLevel: CompatibilityLevel.COMPATIBLE,
      title: 'Asset metadata schema is Cloud Service compatible',
      description: 'Custom metadata schema extensions are compatible with AEM Assets as a Cloud Service.',
      affectedPath: '/conf/acme/settings/dam/adminui-extension/metadataschema',
      remediationGuide: 'No action required.',
      autoFixAvailable: false,
      estimatedHours: 0,
      bpaPatternCode: null,
    },
  ],
  contentHealth: {
    totalPages: 4250,
    totalAssets: 28400,
    totalContentFragments: 340,
    totalExperienceFragments: 125,
    duplicatesDetected: 1240,
    brokenReferences: 89,
    metadataCompleteness: 72,
    structuralIssues: 34,
    totalSizeGB: 145,
    publishedPercentage: 78,
  },
  integrationMap: [
    {
      id: 'int-001',
      name: 'Salesforce CRM',
      type: 'api',
      sourceConfig: {},
      targetConfig: null,
      adobeProduct: AdobeProduct.AEP,
      authType: 'oauth2',
      dataFlow: 'bidirectional',
      criticality: Severity.HIGH,
      autoMigratable: true,
      migrationNotes: 'Reconnect via Adobe Source Connector.',
    },
  ],
  riskFactors: [
    {
      id: 'risk-001',
      severity: Severity.HIGH,
      category: 'Authentication',
      description: 'LDAP dependency requires complete auth architecture redesign',
      probability: 0.9,
      impact: 'Delays migration by 2-3 weeks if not addressed early',
      mitigation: 'Begin IMS/SAML integration in parallel with code modernization phase',
    },
    {
      id: 'risk-002',
      severity: Severity.MEDIUM,
      category: 'Performance',
      description: 'Large asset repository may cause extended content transfer times',
      probability: 0.6,
      impact: 'Content migration phase could exceed estimates by 40%',
      mitigation: 'Use incremental content transfer with CTT and plan off-peak windows',
    },
    {
      id: 'risk-003',
      severity: Severity.LOW,
      category: 'Training',
      description: 'Development team unfamiliar with Cloud Service SDK',
      probability: 0.5,
      impact: 'Minor delays during code modernization phase',
      mitigation: 'Schedule Adobe-led training session before code modernization begins',
    },
  ],
  estimatedTimeline: {
    totalWeeks: 6,
    phases: [
      { phase: PhaseType.ASSESSMENT, durationWeeks: 0.5, startWeek: 0, endWeek: 0.5, parallelizable: false },
      { phase: PhaseType.PLANNING, durationWeeks: 0.5, startWeek: 0.5, endWeek: 1, parallelizable: false },
      { phase: PhaseType.CODE_MODERNIZATION, durationWeeks: 2, startWeek: 1, endWeek: 3, parallelizable: true },
      { phase: PhaseType.CONTENT_MIGRATION, durationWeeks: 1.5, startWeek: 2, endWeek: 3.5, parallelizable: true },
      { phase: PhaseType.INTEGRATION_RECONNECTION, durationWeeks: 1, startWeek: 3, endWeek: 4, parallelizable: true },
      { phase: PhaseType.TESTING, durationWeeks: 1, startWeek: 4, endWeek: 5, parallelizable: false },
      { phase: PhaseType.CUTOVER, durationWeeks: 0.5, startWeek: 5, endWeek: 5.5, parallelizable: false },
      { phase: PhaseType.MONITORING, durationWeeks: 0.5, startWeek: 5.5, endWeek: 6, parallelizable: false },
    ],
    confidenceLevel: 0.82,
  },
  estimatedCost: {
    platformFee: 15000,
    estimatedSIHours: 120,
    estimatedSICost: 30000,
    totalEstimate: 45000,
    currency: 'USD',
  },
  traditionalEstimate: {
    durationWeeks: 18,
    cost: 142000,
    timeSavingsPercent: 67,
    costSavingsPercent: 68,
  },
  recommendations: [
    'Address LDAP authentication blocker in the first sprint to de-risk the migration.',
    'Enable Content Transfer Tool (CTT) incremental sync to minimize content migration downtime.',
    'Convert static templates to editable templates before code modernization phase.',
    'Set up Cloud Manager CI/CD pipeline early for continuous validation.',
    'Plan go-live cutover during a low-traffic weekend window.',
  ],
  createdAt: '2026-01-16T14:30:00Z',
};

// ============================================================
// Recent Activity
// ============================================================

export const mockActivity: ActivityEntry[] = [
  {
    id: 'act-001',
    migrationId: 'mig-001',
    migrationName: 'Acme Corp AEM Cloud Migration',
    action: 'Content batch migrated',
    timestamp: '2026-03-20T15:30:00Z',
    details: '2,450 pages transferred successfully. 12 assets require manual review.',
  },
  {
    id: 'act-002',
    migrationId: 'mig-005',
    migrationName: 'HealthPlus Campaign v8 Upgrade',
    action: 'Validation phase started',
    timestamp: '2026-03-20T14:15:00Z',
    details: 'Running automated validation suite across 234 workflow configurations.',
  },
  {
    id: 'act-003',
    migrationId: 'mig-006',
    migrationName: 'MediaGroup DAM Consolidation',
    action: 'Asset transformation in progress',
    timestamp: '2026-03-20T12:00:00Z',
    details: 'Processing 1.25M assets. Current batch: 562,000 of 1,250,000 (45%).',
  },
  {
    id: 'act-004',
    migrationId: 'mig-003',
    migrationName: 'TechStart WordPress to AEM EDS',
    action: 'Assessment initiated',
    timestamp: '2026-03-19T10:00:00Z',
    details: 'Scanning WordPress site structure, plugins, and content inventory.',
  },
  {
    id: 'act-005',
    migrationId: 'mig-004',
    migrationName: 'RetailMax Shopify to Adobe Commerce',
    action: 'Planning phase completed',
    timestamp: '2026-03-18T16:45:00Z',
    details: 'Migration plan finalized. 18,500 products mapped to Adobe Commerce catalog.',
  },
  {
    id: 'act-006',
    migrationId: 'mig-002',
    migrationName: 'GlobalBank Analytics to CJA',
    action: 'Migration completed',
    timestamp: '2026-01-20T12:00:00Z',
    details: 'All 12 properties migrated. 45 custom dimensions mapped. Time saved: 71%.',
  },
];

// ============================================================
// Chart Data (Migration activity over past 6 months)
// ============================================================

export const mockChartData = [
  { month: 'Oct', migrations: 4, completed: 3, items: 18200 },
  { month: 'Nov', migrations: 6, completed: 4, items: 31500 },
  { month: 'Dec', migrations: 5, completed: 5, items: 42800 },
  { month: 'Jan', migrations: 8, completed: 7, items: 56300 },
  { month: 'Feb', migrations: 10, completed: 6, items: 68900 },
  { month: 'Mar', migrations: 12, completed: 6, items: 84650 },
];

// ============================================================
// Readiness Scores by Product
// ============================================================

export const mockReadinessScores = [
  { product: 'AEM Sites', score: 74, icon: AdobeProduct.AEM_SITES },
  { product: 'AEM Assets', score: 85, icon: AdobeProduct.AEM_ASSETS },
  { product: 'Analytics / CJA', score: 91, icon: AdobeProduct.CJA },
  { product: 'Campaign', score: 68, icon: AdobeProduct.CAMPAIGN },
  { product: 'Real-Time CDP', score: 82, icon: AdobeProduct.RTCDP },
  { product: 'Commerce', score: 56, icon: AdobeProduct.COMMERCE },
];
